### ISSUE TITLE
Kind request to rm repo...

### ISSUE THREAD

**Issue by dandv** [cineris/poly-rating#1]
...since it shows up among [legit](https://github.com/PolymerLabs/star-ratings) search [results](https://github.com/cmartinezv/star-rating) for Polymer (or other) [rating components](https://github.com/ampproject/amphtml/issues/2691).

**Comment by cineris** [comment]
I will take it down. This was intended to be a legit rating component for polymer. But then my attention was pulled elsewhere. I forgot this even existed.
